name: split_it
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0

  #firebase
  firebase_core: ^1.2.0

  #SocialLogin
  google_sign_in: ^5.0.4

  #Social Apple
  sign_in_with_apple: ^3.0.0

  mocktail: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
